### ISSUE TITLE
Store Commerce Offline Mode Custom proxy issue (Can't find manager)

### ISSUE THREAD

**Issue by zubair1599** [microsoft/Dynamics365Commerce.InStore#24]
Hi Product Team,
We are facing issue when we are installing customized installer on top off base Store Commerce App (offline). The package installs successfully but it is failing to call custom api's in local CRT. We see there are some samples generating custom proxies to call local crt but it is not included in generated installer. We are getting errors on all our customizations 

Retail proxy client offline request failed. RequestUri: crt://offline/CustomDataManager/GetCustomerAccounts?queryResultSettings=SCRUBBED&accountNum=SCRUBBED&%24locale=SCRUBBED. Exception: System.InvalidOperationException: Can't find manager (CustomDataManager) with method (GetCustomerAccounts) with parameter count (2)
   at Microsoft.Dynamics.Commerce.RetailProxy.Adapters.AdaptorCaller.<CallCommerceRuntimeAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Commerce.RetailProxy.Adapters.AdaptorCaller.<ExecuteAsync>d__26.MoveNext().

**Comment by cdhawan** [comment]
@zubair1599,

In most cases this issue is followed by an error during initialization. The initialization error provides more information why Store Commerce failed to create this manager.

If you are seeing "sequence contains no elements" in the Initialization error, make sure your Commerce entity that is bound to the controller is using Key Attribute type from "System.ComponentModel.DataAnnotations" namespace rather "Microsoft.Dynamics.Commerce.Runtime.ComponentModel.DataAnnotations" 

E.g.

If controller is bound to 'Entities.DataModel.ExampleEntity'

```
  [BindEntity(typeof(Entities.DataModel.ExampleEntity))]
  public class BoundController : IController
  ...
```
then key entity should use following attribute.

```
    using SystemAnnotations = System.ComponentModel.DataAnnotations;

    public class ExampleEntity : CommerceEntity
    {
        [SystemAnnotations.Key]
        public string ExampleField
        ...
```
