### ISSUE TITLE
Is it possible to have single installer for multiple project in Store commerce..

### ISSUE THREAD

**Issue by chmasade** [microsoft/Dynamics365Commerce.InStore#29]
Hello everyone,

Good Day!!!

We are migrating Retail SDK to Store Commerce, and having below query...

Request your help here...

We like to add multiple projects with single installer, but getting deployment issue as it is deploying only one project (i.e last project in the solution). Is that we are missing something here. Can you please advise?
Issue like while adding multiple project reference in a single pos extension installer, it is deploying only one project in the extension folder of d365.

Thanks,
Chaya Masade

**Comment by lukedgr** [comment]
Hi @chmasade , unfortunately it is not supported to use a single installer project for multiple Store Commerce extension packages. However, we recommend that each extension package should have its own installer so that it can be installed/updated independently from other extensions. This is one of the key benefits of the independent installer model.

**Comment by chmasade** [comment]
Thank you very much for the inputs @lukedgr
